# action.yml
name: 'Run Statiq.RevealJS'
description: 'Create a reveal.js slidedesk using Statiq'
inputs:
  input-path: 
    description: 'Path for the *.rsd files'
    required: true
  output-path: 
    description: 'Path where the slidedesk created in'
    required: true
    default: 'out'
  slides-path: 
    description: 'Base-Path where the slides located'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/fpommerening/statiq.revealjs:v4.0.0'
  args:
    - ${{ inputs.input-path }}
    - ${{ inputs.slides-path }}
    - ${{ inputs.output-path }}
